standalone-install-test:
  image: python:3.9-bullseye
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script:
    - pip install .
    - echo -e "UC_SAS_VASCARCAT='/dev/null'\nUC_LUSTRE_VASCARCAT='/dev/null'\nUC_VASCA_TEST_RESOURCES='.'"  > .env
    - pytest -v --cov=vasca
    - coverage report
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
