standalone-install-test:
  image: python:3.9-bullseye
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install .
    - echo "UC_SAS_UVVARCAT='/dev/null'\nUC_LUSTRE_UVVARCAT='/dev/null'\nUC_UVVA_TEST_RESOURCES='.'"  > .env
    - pwd
    - ls -a
    - cat .env
    - pytest
