name: uc_uvva
channels:
  - astropy
  - conda-forge
  - defaults
dependencies:
  - astropy=5
  - spyder=5
  - astroquery
  - widgetsnbextension
  - pytest
  - loguru
  - healpy
  - scikit-learn
  - python-dotenv
  - pandas
