# TOML specification: https://toml.io/en/v1.0.0

authors = "UC Science"
commet = """\
         The quick brown \
         fox jumps over \
         the lazy dog.\
         """

# -------- OBSERVATION ----------------------------------------------------------------#

[observations]
instrument = "GALEX"
filter = "NUV"
field_ids = [
    2604912508670050304,  # PS_COSMOS_MOS21
    2604982877414227968,  # PS_COSMOS_MOS22
    2605053246158405632,  # PS_COSMOS_MOS23
    2605123614902583296,  # PS_COSMOS_MOS24
    2605193983646760960,  # PS_COSMOS_MOS25
    2605264352416104448,  # PS_COSMOS_MOS26
    2605334721135116288,  # PS_COSMOS_MOS27
]

# -------- CLUSTERING -----------------------------------------------------------------#

[clustering.meanshift]
bandwidth = None  # Meanshift bandwidth

# -------- SELECTION ------------------------------------------------------------------#

[selection]

[selection.detections]
mag = [18.0, +inf]
mag_err = [0.0, 1.0]
s2n = [5.0, +inf]
artifacts = [2, 3, 4, 9, 42]

[selection.sources]
dmag_max = [0.5, +inf]

# -------- DIAGNOSTICS ----------------------------------------------------------------#

[diagnostics]
level = "AFTERCUTS"  # Choose from ["NONE", "AFTERPRECUTS", "AFTERCUTS"]

[diagnostics.observations]
[diagnostics.detections]
[diagnostics.sources]

# -------- Run ------------------------------------------------------------------------#

[run]

loglevel = "DEBUG"  # Choose one from ["NONE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
logfile = '~/logfile.txt'  # Logfile location
showfigs = true  # Toggle interactive plotting
diagnostics = true  # Toggle diagnostics
outdir = 'dev/null'  # Results location
