authors = "UC science"
commet = """comment"""

[general]
out_dir       = "CWD"                # If "CWD" current work directory will be used
log_level     = "DEBUG"              #["NONE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
log_file      = "uvva.log"           # Will be written into "out_dir"
         
[observations]
observatory = "GALEX"
obs_filter = "NUV"
field_ids = [
    2604912508670050304,  # PS_COSMOS_MOS21
    2604982877414227968,  # PS_COSMOS_MOS22
]
