authors = "UC science"
commet = """Example configuration file"""

[general]
name          = "example_fields"
out_dir       = "./examples/uvva_pipeline"                 # If "CWD" current work directory will be used
log_level     = "DEBUG"                                    #["NONE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
log_file      = "uvva.log"                                 # Will be written into "out_dir"
data_source   = "MAST"                                     # Either "MAST" (cached or online) or "UVVA"

[cluster_mean_shift]
bandwidth     = "None"
seeds         = "None"
bin_seeding   = false
min_bin_freq  = 1
cluster_all   = true
n_jobs        = "None"
max_iter      = 300
         
[observations]
observatory = "GALEX"
obs_filter = "NUV"
field_ids = [
    2604912508670050304,  # PS_COSMOS_MOS21
    2604982877414227968,  # PS_COSMOS_MOS22
]
